{
 "title": "Four Keys",
 "time": { "from": "2022-08-01T03:00:00.000Z", "to": "now" },
 "panels": [
  {
   "title": "Lead Time for Changes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "location": "US",
     "project": "gglobo-deployment-frq-hdg-prd",
     "rawSql": "SELECT \n    DAY, \n    IFNULL(ANY_VALUE(med_time_to_change)/60, 0) AS median_time_to_change \nFROM \n(\n    SELECT\n        pull_request_id, \n        TIMESTAMP_TRUNC(PARSE_TIMESTAMP('%Y-%m-%dT%H:%M:%SZ', first_commit_time), DAY) AS DAY, \n        PERCENTILE_CONT(\n            IF(\n                TIMESTAMP_DIFF(\n                    PARSE_TIMESTAMP('%Y-%m-%dT%H:%M:%SZ', main_merged_time), \n                    PARSE_TIMESTAMP('%Y-%m-%dT%H:%M:%SZ', first_commit_time), \n                    MINUTE) > 0, \n                TIMESTAMP_DIFF(\n                    PARSE_TIMESTAMP('%Y-%m-%dT%H:%M:%SZ', main_merged_time), \n                    PARSE_TIMESTAMP('%Y-%m-%dT%H:%M:%SZ', first_commit_time), \n                    MINUTE), \n                NULL\n            ), \n            0.5\n        ) OVER (\n            PARTITION BY TIMESTAMP_TRUNC(PARSE_TIMESTAMP('%Y-%m-%dT%H:%M:%SZ', first_commit_time), DAY)\n        ) AS med_time_to_change\n    FROM `four_keys.main_deployments`\n)\nGROUP BY \n    DAY\nORDER BY \n    DAY"
    }
   ]
  },
  {
   "title": "Lead Time to Change Bucket",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "US",
     "project": "gglobo-deployment-frq-hdg-prd",
     "rawSql": "SELECT \n CASE\n  WHEN median_time_to_change < 24 * 60 then \"One day\"\n  WHEN median_time_to_change < 168 * 60 then \"One week\"\n  WHEN median_time_to_change < 730 * 60 then \"One month\"\n  WHEN median_time_to_change < 730 * 6 * 60 then \"Six months\"\n  ELSE \"One year\"\n END as lead_time_to_change\nFROM (\n SELECT\n  IFNULL(ANY_VALUE(med_time_to_change), 0) AS median_time_to_change\n FROM (\n   SELECT\n    PERCENTILE_CONT(\n     IF(TIMESTAMP_DIFF(PARSE_TIMESTAMP('%Y-%m-%dT%H:%M:%SZ', main_merged_time), PARSE_TIMESTAMP('%Y-%m-%dT%H:%M:%SZ', first_commit_time), MINUTE) > 0, \n     TIMESTAMP_DIFF(PARSE_TIMESTAMP('%Y-%m-%dT%H:%M:%SZ', main_merged_time), PARSE_TIMESTAMP('%Y-%m-%dT%H:%M:%SZ', first_commit_time), MINUTE), NULL),\n     0.5) \n     OVER () AS med_time_to_change\n   FROM `cw-spc-fourkeys.four_keys.main_deployments`\n   WHERE PARSE_TIMESTAMP('%Y-%m-%dT%H:%M:%SZ', first_commit_time) > TIMESTAMP(DATE_SUB(CURRENT_DATE(), INTERVAL 3 MONTH))\n )\n)"
    }
   ]
  },
  {
   "title": "Daily Deployments",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 13, "y": 0 },
   "targets": [
    {
     "location": "US",
     "project": "gglobo-deployment-frq-hdg-prd",
     "rawSql": "SELECT\n    TIMESTAMP_TRUNC(PARSE_TIMESTAMP('%Y-%m-%dT%H:%M:%SZ', main_merged_time), DAY) AS time,\n    COUNT(DISTINCT pull_request_id) AS metric\nFROM\n    `four_keys.main_deployments`\nGROUP BY\n    time\nORDER BY\n    time"
    }
   ]
  },
  {
   "title": "Deployment Frequency",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "US",
     "project": "gglobo-deployment-frq-hdg-prd",
     "rawSql": "WITH last_three_months AS (\n    SELECT\n        TIMESTAMP(day) AS day\n    FROM\n        UNNEST(\n            GENERATE_DATE_ARRAY(\n                DATE_SUB(CURRENT_DATE(), INTERVAL 3 MONTH), \n                CURRENT_DATE(),\n                INTERVAL 1 DAY\n            )\n        ) AS day\n)\n\nSELECT\n    CASE \n        WHEN daily THEN \"Daily\"\n        WHEN weekly THEN \"Weekly\"\n        WHEN PERCENTILE_CONT(monthly_deploys, 0.5) OVER () >= 1 THEN \"Monthly\"\n        ELSE \"Yearly\"\n    END as deployment_frequency\nFROM (\n    SELECT\n        PERCENTILE_CONT(days_deployed, 0.5) OVER() >= 3 AS daily,\n        PERCENTILE_CONT(week_deployed, 0.5) OVER() >= 1 AS weekly,\n        SUM(week_deployed) OVER(partition by TIMESTAMP_TRUNC(week, MONTH)) monthly_deploys\n    FROM(\n        SELECT\n            TIMESTAMP_TRUNC(last_three_months.day, WEEK) as week,\n            MAX(if(feature_commits.day is not null, 1, 0)) as week_deployed,\n            COUNT(distinct feature_commits.day) as days_deployed\n        FROM \n            last_three_months\n        LEFT JOIN (\n            SELECT\n                TIMESTAMP_TRUNC(PARSE_TIMESTAMP('%Y-%m-%dT%H:%M:%SZ', main_merged_time), DAY) AS day\n            FROM \n                cw-spc-fourkeys.four_keys.main_deployments\n        ) feature_commits \n        ON feature_commits.day = last_three_months.day\n        GROUP BY week\n    )\n)\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Daily Median Time to Restore Services",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 10 },
   "targets": [
    {
     "location": "US",
     "project": "gglobo-deployment-frq-hdg-prd",
     "rawSql": "SELECT\n  TIMESTAMP_TRUNC(time_created, DAY) as day,\n  #### Median time to resolve\n  PERCENTILE_CONT(\n    TIMESTAMP_DIFF(time_resolved, time_created, HOUR), 0.5)\n    OVER(PARTITION BY TIMESTAMP_TRUNC(time_created, DAY)\n    ) as daily_med_time_to_restore,\n  FROM four_keys.incidents\nORDER BY day"
    }
   ]
  },
  {
   "title": "Median Time to Restore Services",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "US",
     "project": "gglobo-deployment-frq-hdg-prd",
     "rawSql": "SELECT\nCASE WHEN med_time_to_resolve < 24  then \"One day\"\n     WHEN med_time_to_resolve < 168  then \"One week\"\n     WHEN med_time_to_resolve < 730  then \"One month\"\n     WHEN med_time_to_resolve < 730 * 6 then \"Six months\"\n     ELSE \"One year\"\n     END as med_time_to_resolve,\nFROM (\n  SELECT\n  #### Median time to resolve\n  PERCENTILE_CONT(\n    TIMESTAMP_DIFF(time_resolved, time_created, HOUR), 0.5)\n    OVER() as med_time_to_resolve,\n  FROM four_keys.incidents\n  # Limit to 3 months\n  WHERE time_created > TIMESTAMP(DATE_SUB(CURRENT_DATE(), INTERVAL 3 MONTH)))\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Daily Change Failure Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 13, "y": 10 },
   "targets": [
    {
     "location": "US",
     "project": "gglobo-deployment-frq-hdg-prd",
     "rawSql": "SELECT\nTIMESTAMP_TRUNC(d.time_created, DAY) as day,\n  IF(COUNT(DISTINCT change_id) = 0,0, SUM(IF(i.incident_id is NULL, 0, 1)) / COUNT(DISTINCT deploy_id)) as change_fail_rate\nFROM four_keys.deployments d, d.changes\nLEFT JOIN four_keys.changes c ON changes = c.change_id\nLEFT JOIN(SELECT\n        DISTINCT incident_id,\n        change,\n        time_resolved\n        FROM four_keys.incidents i,\n        i.changes change) i ON i.change = changes\nGROUP BY day"
    }
   ]
  },
  {
   "title": "Change Failure Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "US",
     "project": "gglobo-deployment-frq-hdg-prd",
     "rawSql": "SELECT\nCASE WHEN change_fail_rate <= .15 then \"0-15%\"\n     WHEN change_fail_rate < .46 then \"16-45%\"\n     ELSE \"46-60%\" end as change_fail_rate\nFROM \n (SELECT\n    IF(COUNT(DISTINCT change_id) = 0,0, SUM(IF(i.incident_id is NULL, 0, 1)) / COUNT(DISTINCT deploy_id)) as change_fail_rate\n  FROM four_keys.deployments d, d.changes\n  LEFT JOIN four_keys.changes c ON changes = c.change_id\n  LEFT JOIN(SELECT\n          incident_id,\n          change,\n          time_resolved\n          FROM four_keys.incidents i,\n          i.changes change) i ON i.change = changes\n  # Limit to 3 months\n  WHERE d.time_created > TIMESTAMP(DATE_SUB(CURRENT_DATE(), INTERVAL 3 MONTH))\n  )\nLIMIT 1"
    }
   ]
  }
 ]
}